spring :
  application.name : consumer-service-1
  rabbitmq :
    host : localhost
    port : 5672
    username : veeru
    password : veeru123

       
       
server:
  port: 5152
  
  
logging:
     level: 
         org.springframework.web: Info